spring:
  datasource:
    url: jdbc:h2:mem:CODESUPPORT
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
upload:
  host-name: http://localhost:8082
  image:
    max-size: 1000
security:
  discord:
    client-id: 1234
    secret: 4321
    redirect-uri: http://localhost:8082/actuator/health
  http:
    cookie:
      name: ${cookie.name:AccessToken}
      max-age: ${cookie.max.age:600} #10 min
      secure: true
    cors:
      origins:
        - ${cors.origin:http://localhost:3000}
      credentialsAllowed: true
healthcheck:
  ping:
    url: http://localhost:8082/actuator/health
    delay: 5000