spring:
  profiles:
    active: @active.spring.profile@
  jpa:
    hibernate:
      naming:
        physical-strategy: dev.codesupport.web.common.service.data.DataPhysicalNamingStrategy
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
upload:
  host-name: ${api.hostname:}
  image:
    max-size: ${max.image.size:512000} #default is 500kB
security:
  discord:
    client-id: ${discord.app.id:}
    secret: ${discord.app.secret:}
    redirect-uri: ${discord.app.redirect:}
  http:
    cookie:
      name: ${cookie.name:}
      max-age: ${cookie.max.age:}
    cors:
      origins:
        - ${cors.origin:}
      methods:
        - "*"
server:
  port: 8082