spring:
  profiles:
    active: @active.spring.profile@
  jpa:
    hibernate:
      naming:
        physical-strategy: dev.codesupport.web.common.service.data.DataPhysicalNamingStrategy
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
upload:
  image:
    max-size: ${max.image.size:512000} #default is 500kB
security:
  jwt:
    issuer: ${jwt.issuer:codesupport.dev}
    expiration: ${jwt.expiration:10m}
  discord:
    client-id: ${discord.app.id:}
    secret: ${discord.app.secret:}
    redirect-uri: ${discord.app.redirect:}
server:
  port: 8082