spring:
  profiles:
    active: @active.spring.profile@
  jpa:
    hibernate:
      naming:
        physical-strategy: dev.codesupport.web.common.service.data.DataPhysicalNamingStrategy
security:
  jwt:
    issuer: ${jwt.issuer:CodeSupport.dev}
    expiration: ${jwt.expiration:10m}
logging:
  level:
    root: WARN
    org.springframework: ${log.root.level:INFO}
    dev.codesupport: ${log.local.level:DEBUG}
#    org.springframework.transaction: TRACE
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5p] | %-28c{1} | - %m%n"
server:
  port: 8082